### PR TITLE
We need Ruby too.

### PR DESCRIPTION
**Pull request by ioquatix**
It would be good to write some basic tests to validate this extension is working correctly.

### CODE REVIEW

**Comment by ioquatix** [comment]
@connor4312 I'm not really sure how to write a basic test to check that my tests are showing up in the test list. Are you able to give me some ideas or point me in the right direction?

**Comment by connor4312** [comment]
There's no a super easy way to get this, you can look at how I wrote tests for this in one of my test runners for inspiration though. Best way is just introspecting the controller's items. https://github.com/connor4312/nodejs-testing/blob/main/testCases/modules/runner.ts

**Comment by ioquatix** [comment]
That looks pretty good to me, thanks. I'll try it out.

**Comment by ioquatix** [comment]
@connor4312 you might be interested in this test.

I figured out you can get the extension, and the object returned by activate, which in my case, is the list of project (controllers) for the test runners. It's enough for me to test that the items were loaded and confirm the basic functionality and avoids the need for the test command that you used to get the controller of your extension.

**Pull request merged**
